# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/projects/reader

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/projects/reader

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/projects/reader/CMakeFiles /home/pi/projects/reader/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/projects/reader/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NxpRdLibLinuxPN512

# Build rule for target.
NxpRdLibLinuxPN512: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NxpRdLibLinuxPN512
.PHONY : NxpRdLibLinuxPN512

# fast build rule for target.
NxpRdLibLinuxPN512/fast:
	$(MAKE) -f linux/CMakeFiles/NxpRdLibLinuxPN512.dir/build.make linux/CMakeFiles/NxpRdLibLinuxPN512.dir/build
.PHONY : NxpRdLibLinuxPN512/fast

#=============================================================================
# Target rules for targets named NxpRdLibLinuxPN5180

# Build rule for target.
NxpRdLibLinuxPN5180: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NxpRdLibLinuxPN5180
.PHONY : NxpRdLibLinuxPN5180

# fast build rule for target.
NxpRdLibLinuxPN5180/fast:
	$(MAKE) -f linux/CMakeFiles/NxpRdLibLinuxPN5180.dir/build.make linux/CMakeFiles/NxpRdLibLinuxPN5180.dir/build
.PHONY : NxpRdLibLinuxPN5180/fast

#=============================================================================
# Target rules for targets named NxpRdLibLinuxRC663

# Build rule for target.
NxpRdLibLinuxRC663: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NxpRdLibLinuxRC663
.PHONY : NxpRdLibLinuxRC663

# fast build rule for target.
NxpRdLibLinuxRC663/fast:
	$(MAKE) -f linux/CMakeFiles/NxpRdLibLinuxRC663.dir/build.make linux/CMakeFiles/NxpRdLibLinuxRC663.dir/build
.PHONY : NxpRdLibLinuxRC663/fast

#=============================================================================
# Target rules for targets named NfcrdlibEx1_BasicDiscoveryLoopPN512

# Build rule for target.
NfcrdlibEx1_BasicDiscoveryLoopPN512: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcrdlibEx1_BasicDiscoveryLoopPN512
.PHONY : NfcrdlibEx1_BasicDiscoveryLoopPN512

# fast build rule for target.
NfcrdlibEx1_BasicDiscoveryLoopPN512/fast:
	$(MAKE) -f examples/NfcrdlibEx1_BasicDiscoveryLoop/CMakeFiles/NfcrdlibEx1_BasicDiscoveryLoopPN512.dir/build.make examples/NfcrdlibEx1_BasicDiscoveryLoop/CMakeFiles/NfcrdlibEx1_BasicDiscoveryLoopPN512.dir/build
.PHONY : NfcrdlibEx1_BasicDiscoveryLoopPN512/fast

#=============================================================================
# Target rules for targets named NfcrdlibEx1_BasicDiscoveryLoopPN5180

# Build rule for target.
NfcrdlibEx1_BasicDiscoveryLoopPN5180: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcrdlibEx1_BasicDiscoveryLoopPN5180
.PHONY : NfcrdlibEx1_BasicDiscoveryLoopPN5180

# fast build rule for target.
NfcrdlibEx1_BasicDiscoveryLoopPN5180/fast:
	$(MAKE) -f examples/NfcrdlibEx1_BasicDiscoveryLoop/CMakeFiles/NfcrdlibEx1_BasicDiscoveryLoopPN5180.dir/build.make examples/NfcrdlibEx1_BasicDiscoveryLoop/CMakeFiles/NfcrdlibEx1_BasicDiscoveryLoopPN5180.dir/build
.PHONY : NfcrdlibEx1_BasicDiscoveryLoopPN5180/fast

#=============================================================================
# Target rules for targets named NfcrdlibEx1_BasicDiscoveryLoopRC663

# Build rule for target.
NfcrdlibEx1_BasicDiscoveryLoopRC663: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcrdlibEx1_BasicDiscoveryLoopRC663
.PHONY : NfcrdlibEx1_BasicDiscoveryLoopRC663

# fast build rule for target.
NfcrdlibEx1_BasicDiscoveryLoopRC663/fast:
	$(MAKE) -f examples/NfcrdlibEx1_BasicDiscoveryLoop/CMakeFiles/NfcrdlibEx1_BasicDiscoveryLoopRC663.dir/build.make examples/NfcrdlibEx1_BasicDiscoveryLoop/CMakeFiles/NfcrdlibEx1_BasicDiscoveryLoopRC663.dir/build
.PHONY : NfcrdlibEx1_BasicDiscoveryLoopRC663/fast

#=============================================================================
# Target rules for targets named NfcrdlibEx2_AdvancedDiscoveryLoopPN512

# Build rule for target.
NfcrdlibEx2_AdvancedDiscoveryLoopPN512: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcrdlibEx2_AdvancedDiscoveryLoopPN512
.PHONY : NfcrdlibEx2_AdvancedDiscoveryLoopPN512

# fast build rule for target.
NfcrdlibEx2_AdvancedDiscoveryLoopPN512/fast:
	$(MAKE) -f examples/NfcrdlibEx2_AdvancedDiscoveryLoop/CMakeFiles/NfcrdlibEx2_AdvancedDiscoveryLoopPN512.dir/build.make examples/NfcrdlibEx2_AdvancedDiscoveryLoop/CMakeFiles/NfcrdlibEx2_AdvancedDiscoveryLoopPN512.dir/build
.PHONY : NfcrdlibEx2_AdvancedDiscoveryLoopPN512/fast

#=============================================================================
# Target rules for targets named NfcrdlibEx2_AdvancedDiscoveryLoopPN5180

# Build rule for target.
NfcrdlibEx2_AdvancedDiscoveryLoopPN5180: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcrdlibEx2_AdvancedDiscoveryLoopPN5180
.PHONY : NfcrdlibEx2_AdvancedDiscoveryLoopPN5180

# fast build rule for target.
NfcrdlibEx2_AdvancedDiscoveryLoopPN5180/fast:
	$(MAKE) -f examples/NfcrdlibEx2_AdvancedDiscoveryLoop/CMakeFiles/NfcrdlibEx2_AdvancedDiscoveryLoopPN5180.dir/build.make examples/NfcrdlibEx2_AdvancedDiscoveryLoop/CMakeFiles/NfcrdlibEx2_AdvancedDiscoveryLoopPN5180.dir/build
.PHONY : NfcrdlibEx2_AdvancedDiscoveryLoopPN5180/fast

#=============================================================================
# Target rules for targets named NfcrdlibEx2_AdvancedDiscoveryLoopRC663

# Build rule for target.
NfcrdlibEx2_AdvancedDiscoveryLoopRC663: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcrdlibEx2_AdvancedDiscoveryLoopRC663
.PHONY : NfcrdlibEx2_AdvancedDiscoveryLoopRC663

# fast build rule for target.
NfcrdlibEx2_AdvancedDiscoveryLoopRC663/fast:
	$(MAKE) -f examples/NfcrdlibEx2_AdvancedDiscoveryLoop/CMakeFiles/NfcrdlibEx2_AdvancedDiscoveryLoopRC663.dir/build.make examples/NfcrdlibEx2_AdvancedDiscoveryLoop/CMakeFiles/NfcrdlibEx2_AdvancedDiscoveryLoopRC663.dir/build
.PHONY : NfcrdlibEx2_AdvancedDiscoveryLoopRC663/fast

#=============================================================================
# Target rules for targets named NfcrdlibEx3_NFCForumPN512

# Build rule for target.
NfcrdlibEx3_NFCForumPN512: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcrdlibEx3_NFCForumPN512
.PHONY : NfcrdlibEx3_NFCForumPN512

# fast build rule for target.
NfcrdlibEx3_NFCForumPN512/fast:
	$(MAKE) -f examples/NfcrdlibEx3_NFCForum/CMakeFiles/NfcrdlibEx3_NFCForumPN512.dir/build.make examples/NfcrdlibEx3_NFCForum/CMakeFiles/NfcrdlibEx3_NFCForumPN512.dir/build
.PHONY : NfcrdlibEx3_NFCForumPN512/fast

#=============================================================================
# Target rules for targets named NfcrdlibEx3_NFCForumPN5180

# Build rule for target.
NfcrdlibEx3_NFCForumPN5180: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcrdlibEx3_NFCForumPN5180
.PHONY : NfcrdlibEx3_NFCForumPN5180

# fast build rule for target.
NfcrdlibEx3_NFCForumPN5180/fast:
	$(MAKE) -f examples/NfcrdlibEx3_NFCForum/CMakeFiles/NfcrdlibEx3_NFCForumPN5180.dir/build.make examples/NfcrdlibEx3_NFCForum/CMakeFiles/NfcrdlibEx3_NFCForumPN5180.dir/build
.PHONY : NfcrdlibEx3_NFCForumPN5180/fast

#=============================================================================
# Target rules for targets named NfcrdlibEx4_MIFAREClassicPN512

# Build rule for target.
NfcrdlibEx4_MIFAREClassicPN512: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcrdlibEx4_MIFAREClassicPN512
.PHONY : NfcrdlibEx4_MIFAREClassicPN512

# fast build rule for target.
NfcrdlibEx4_MIFAREClassicPN512/fast:
	$(MAKE) -f examples/NfcrdlibEx4_MIFAREClassic/CMakeFiles/NfcrdlibEx4_MIFAREClassicPN512.dir/build.make examples/NfcrdlibEx4_MIFAREClassic/CMakeFiles/NfcrdlibEx4_MIFAREClassicPN512.dir/build
.PHONY : NfcrdlibEx4_MIFAREClassicPN512/fast

#=============================================================================
# Target rules for targets named NfcrdlibEx4_MIFAREClassicPN5180

# Build rule for target.
NfcrdlibEx4_MIFAREClassicPN5180: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcrdlibEx4_MIFAREClassicPN5180
.PHONY : NfcrdlibEx4_MIFAREClassicPN5180

# fast build rule for target.
NfcrdlibEx4_MIFAREClassicPN5180/fast:
	$(MAKE) -f examples/NfcrdlibEx4_MIFAREClassic/CMakeFiles/NfcrdlibEx4_MIFAREClassicPN5180.dir/build.make examples/NfcrdlibEx4_MIFAREClassic/CMakeFiles/NfcrdlibEx4_MIFAREClassicPN5180.dir/build
.PHONY : NfcrdlibEx4_MIFAREClassicPN5180/fast

#=============================================================================
# Target rules for targets named NfcrdlibEx4_MIFAREClassicRC663

# Build rule for target.
NfcrdlibEx4_MIFAREClassicRC663: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcrdlibEx4_MIFAREClassicRC663
.PHONY : NfcrdlibEx4_MIFAREClassicRC663

# fast build rule for target.
NfcrdlibEx4_MIFAREClassicRC663/fast:
	$(MAKE) -f examples/NfcrdlibEx4_MIFAREClassic/CMakeFiles/NfcrdlibEx4_MIFAREClassicRC663.dir/build.make examples/NfcrdlibEx4_MIFAREClassic/CMakeFiles/NfcrdlibEx4_MIFAREClassicRC663.dir/build
.PHONY : NfcrdlibEx4_MIFAREClassicRC663/fast

#=============================================================================
# Target rules for targets named NfcrdlibEx5_ISO15693PN5180

# Build rule for target.
NfcrdlibEx5_ISO15693PN5180: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcrdlibEx5_ISO15693PN5180
.PHONY : NfcrdlibEx5_ISO15693PN5180

# fast build rule for target.
NfcrdlibEx5_ISO15693PN5180/fast:
	$(MAKE) -f examples/NfcrdlibEx5_ISO15693/CMakeFiles/NfcrdlibEx5_ISO15693PN5180.dir/build.make examples/NfcrdlibEx5_ISO15693/CMakeFiles/NfcrdlibEx5_ISO15693PN5180.dir/build
.PHONY : NfcrdlibEx5_ISO15693PN5180/fast

#=============================================================================
# Target rules for targets named NfcrdlibEx5_ISO15693RC663

# Build rule for target.
NfcrdlibEx5_ISO15693RC663: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcrdlibEx5_ISO15693RC663
.PHONY : NfcrdlibEx5_ISO15693RC663

# fast build rule for target.
NfcrdlibEx5_ISO15693RC663/fast:
	$(MAKE) -f examples/NfcrdlibEx5_ISO15693/CMakeFiles/NfcrdlibEx5_ISO15693RC663.dir/build.make examples/NfcrdlibEx5_ISO15693/CMakeFiles/NfcrdlibEx5_ISO15693RC663.dir/build
.PHONY : NfcrdlibEx5_ISO15693RC663/fast

#=============================================================================
# Target rules for targets named NfcrdlibEx6_EMVCo_LoopbackPN512

# Build rule for target.
NfcrdlibEx6_EMVCo_LoopbackPN512: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcrdlibEx6_EMVCo_LoopbackPN512
.PHONY : NfcrdlibEx6_EMVCo_LoopbackPN512

# fast build rule for target.
NfcrdlibEx6_EMVCo_LoopbackPN512/fast:
	$(MAKE) -f examples/NfcrdlibEx6_EMVCo_Loopback/CMakeFiles/NfcrdlibEx6_EMVCo_LoopbackPN512.dir/build.make examples/NfcrdlibEx6_EMVCo_Loopback/CMakeFiles/NfcrdlibEx6_EMVCo_LoopbackPN512.dir/build
.PHONY : NfcrdlibEx6_EMVCo_LoopbackPN512/fast

#=============================================================================
# Target rules for targets named NfcrdlibEx6_EMVCo_LoopbackPN5180

# Build rule for target.
NfcrdlibEx6_EMVCo_LoopbackPN5180: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcrdlibEx6_EMVCo_LoopbackPN5180
.PHONY : NfcrdlibEx6_EMVCo_LoopbackPN5180

# fast build rule for target.
NfcrdlibEx6_EMVCo_LoopbackPN5180/fast:
	$(MAKE) -f examples/NfcrdlibEx6_EMVCo_Loopback/CMakeFiles/NfcrdlibEx6_EMVCo_LoopbackPN5180.dir/build.make examples/NfcrdlibEx6_EMVCo_Loopback/CMakeFiles/NfcrdlibEx6_EMVCo_LoopbackPN5180.dir/build
.PHONY : NfcrdlibEx6_EMVCo_LoopbackPN5180/fast

#=============================================================================
# Target rules for targets named NfcrdlibEx6_EMVCo_LoopbackRC663

# Build rule for target.
NfcrdlibEx6_EMVCo_LoopbackRC663: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcrdlibEx6_EMVCo_LoopbackRC663
.PHONY : NfcrdlibEx6_EMVCo_LoopbackRC663

# fast build rule for target.
NfcrdlibEx6_EMVCo_LoopbackRC663/fast:
	$(MAKE) -f examples/NfcrdlibEx6_EMVCo_Loopback/CMakeFiles/NfcrdlibEx6_EMVCo_LoopbackRC663.dir/build.make examples/NfcrdlibEx6_EMVCo_Loopback/CMakeFiles/NfcrdlibEx6_EMVCo_LoopbackRC663.dir/build
.PHONY : NfcrdlibEx6_EMVCo_LoopbackRC663/fast

#=============================================================================
# Target rules for targets named NfcrdlibEx7_EMVCo_PollingPN512

# Build rule for target.
NfcrdlibEx7_EMVCo_PollingPN512: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcrdlibEx7_EMVCo_PollingPN512
.PHONY : NfcrdlibEx7_EMVCo_PollingPN512

# fast build rule for target.
NfcrdlibEx7_EMVCo_PollingPN512/fast:
	$(MAKE) -f examples/NfcrdlibEx7_EMVCo_Polling/CMakeFiles/NfcrdlibEx7_EMVCo_PollingPN512.dir/build.make examples/NfcrdlibEx7_EMVCo_Polling/CMakeFiles/NfcrdlibEx7_EMVCo_PollingPN512.dir/build
.PHONY : NfcrdlibEx7_EMVCo_PollingPN512/fast

#=============================================================================
# Target rules for targets named NfcrdlibEx7_EMVCo_PollingPN5180

# Build rule for target.
NfcrdlibEx7_EMVCo_PollingPN5180: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcrdlibEx7_EMVCo_PollingPN5180
.PHONY : NfcrdlibEx7_EMVCo_PollingPN5180

# fast build rule for target.
NfcrdlibEx7_EMVCo_PollingPN5180/fast:
	$(MAKE) -f examples/NfcrdlibEx7_EMVCo_Polling/CMakeFiles/NfcrdlibEx7_EMVCo_PollingPN5180.dir/build.make examples/NfcrdlibEx7_EMVCo_Polling/CMakeFiles/NfcrdlibEx7_EMVCo_PollingPN5180.dir/build
.PHONY : NfcrdlibEx7_EMVCo_PollingPN5180/fast

#=============================================================================
# Target rules for targets named NfcrdlibEx7_EMVCo_PollingRC663

# Build rule for target.
NfcrdlibEx7_EMVCo_PollingRC663: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcrdlibEx7_EMVCo_PollingRC663
.PHONY : NfcrdlibEx7_EMVCo_PollingRC663

# fast build rule for target.
NfcrdlibEx7_EMVCo_PollingRC663/fast:
	$(MAKE) -f examples/NfcrdlibEx7_EMVCo_Polling/CMakeFiles/NfcrdlibEx7_EMVCo_PollingRC663.dir/build.make examples/NfcrdlibEx7_EMVCo_Polling/CMakeFiles/NfcrdlibEx7_EMVCo_PollingRC663.dir/build
.PHONY : NfcrdlibEx7_EMVCo_PollingRC663/fast

#=============================================================================
# Target rules for targets named NfcrdlibEx8_HCE_T4TPN512

# Build rule for target.
NfcrdlibEx8_HCE_T4TPN512: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcrdlibEx8_HCE_T4TPN512
.PHONY : NfcrdlibEx8_HCE_T4TPN512

# fast build rule for target.
NfcrdlibEx8_HCE_T4TPN512/fast:
	$(MAKE) -f examples/NfcrdlibEx8_HCE_T4T/CMakeFiles/NfcrdlibEx8_HCE_T4TPN512.dir/build.make examples/NfcrdlibEx8_HCE_T4T/CMakeFiles/NfcrdlibEx8_HCE_T4TPN512.dir/build
.PHONY : NfcrdlibEx8_HCE_T4TPN512/fast

#=============================================================================
# Target rules for targets named NfcrdlibEx8_HCE_T4TPN5180

# Build rule for target.
NfcrdlibEx8_HCE_T4TPN5180: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcrdlibEx8_HCE_T4TPN5180
.PHONY : NfcrdlibEx8_HCE_T4TPN5180

# fast build rule for target.
NfcrdlibEx8_HCE_T4TPN5180/fast:
	$(MAKE) -f examples/NfcrdlibEx8_HCE_T4T/CMakeFiles/NfcrdlibEx8_HCE_T4TPN5180.dir/build.make examples/NfcrdlibEx8_HCE_T4T/CMakeFiles/NfcrdlibEx8_HCE_T4TPN5180.dir/build
.PHONY : NfcrdlibEx8_HCE_T4TPN5180/fast

#=============================================================================
# Target rules for targets named NfcrdlibEx9_NTagI2CPN512

# Build rule for target.
NfcrdlibEx9_NTagI2CPN512: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcrdlibEx9_NTagI2CPN512
.PHONY : NfcrdlibEx9_NTagI2CPN512

# fast build rule for target.
NfcrdlibEx9_NTagI2CPN512/fast:
	$(MAKE) -f examples/NfcrdlibEx9_NTagI2C/CMakeFiles/NfcrdlibEx9_NTagI2CPN512.dir/build.make examples/NfcrdlibEx9_NTagI2C/CMakeFiles/NfcrdlibEx9_NTagI2CPN512.dir/build
.PHONY : NfcrdlibEx9_NTagI2CPN512/fast

#=============================================================================
# Target rules for targets named NfcrdlibEx9_NTagI2CPN5180

# Build rule for target.
NfcrdlibEx9_NTagI2CPN5180: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcrdlibEx9_NTagI2CPN5180
.PHONY : NfcrdlibEx9_NTagI2CPN5180

# fast build rule for target.
NfcrdlibEx9_NTagI2CPN5180/fast:
	$(MAKE) -f examples/NfcrdlibEx9_NTagI2C/CMakeFiles/NfcrdlibEx9_NTagI2CPN5180.dir/build.make examples/NfcrdlibEx9_NTagI2C/CMakeFiles/NfcrdlibEx9_NTagI2CPN5180.dir/build
.PHONY : NfcrdlibEx9_NTagI2CPN5180/fast

#=============================================================================
# Target rules for targets named NfcrdlibEx9_NTagI2CRC663

# Build rule for target.
NfcrdlibEx9_NTagI2CRC663: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcrdlibEx9_NTagI2CRC663
.PHONY : NfcrdlibEx9_NTagI2CRC663

# fast build rule for target.
NfcrdlibEx9_NTagI2CRC663/fast:
	$(MAKE) -f examples/NfcrdlibEx9_NTagI2C/CMakeFiles/NfcrdlibEx9_NTagI2CRC663.dir/build.make examples/NfcrdlibEx9_NTagI2C/CMakeFiles/NfcrdlibEx9_NTagI2CRC663.dir/build
.PHONY : NfcrdlibEx9_NTagI2CRC663/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... NxpRdLibLinuxPN512"
	@echo "... NxpRdLibLinuxPN5180"
	@echo "... NxpRdLibLinuxRC663"
	@echo "... NfcrdlibEx1_BasicDiscoveryLoopPN512"
	@echo "... NfcrdlibEx1_BasicDiscoveryLoopPN5180"
	@echo "... NfcrdlibEx1_BasicDiscoveryLoopRC663"
	@echo "... NfcrdlibEx2_AdvancedDiscoveryLoopPN512"
	@echo "... NfcrdlibEx2_AdvancedDiscoveryLoopPN5180"
	@echo "... NfcrdlibEx2_AdvancedDiscoveryLoopRC663"
	@echo "... NfcrdlibEx3_NFCForumPN512"
	@echo "... NfcrdlibEx3_NFCForumPN5180"
	@echo "... NfcrdlibEx4_MIFAREClassicPN512"
	@echo "... NfcrdlibEx4_MIFAREClassicPN5180"
	@echo "... NfcrdlibEx4_MIFAREClassicRC663"
	@echo "... NfcrdlibEx5_ISO15693PN5180"
	@echo "... NfcrdlibEx5_ISO15693RC663"
	@echo "... NfcrdlibEx6_EMVCo_LoopbackPN512"
	@echo "... NfcrdlibEx6_EMVCo_LoopbackPN5180"
	@echo "... NfcrdlibEx6_EMVCo_LoopbackRC663"
	@echo "... NfcrdlibEx7_EMVCo_PollingPN512"
	@echo "... NfcrdlibEx7_EMVCo_PollingPN5180"
	@echo "... NfcrdlibEx7_EMVCo_PollingRC663"
	@echo "... NfcrdlibEx8_HCE_T4TPN512"
	@echo "... NfcrdlibEx8_HCE_T4TPN5180"
	@echo "... NfcrdlibEx9_NTagI2CPN512"
	@echo "... NfcrdlibEx9_NTagI2CPN5180"
	@echo "... NfcrdlibEx9_NTagI2CRC663"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

