#ifndef NXPRDLIB_VERSION_INFO_H_INCLUDED
#define NXPRDLIB_VERSION_INFO_H_INCLUDED


/*
 *                  Copyright (c), NXP Semiconductors
 *
 *                     (C)NXP Semiconductors
 *       All rights are reserved. Reproduction in whole or in part is
 *      prohibited without the written consent of the copyright owner.
 *  NXP reserves the right to make changes without notice at any time.
 * NXP makes no warranty, expressed, implied or statutory, including but
 * not limited to any implied warranty of merchantability or fitness for any
 *particular purpose, or that the use will not infringe any third party patent,
 * copyright or trademark. NXP must not be liable for any loss or damage
 *                          arising from its use.
 */
/*
 * Version Information
 * Auto-Generated by:
 *     docs\22_rel_doc\version_update.py (v2014.07.20_00)
 *
 * Do not edit this file. Update version_info.txt instead. */


#define NxpRdLib_VER_FILEDESCRIPTION     "NxpRdLib_4.010.03.001609_NExC"
#define NxpRdLib_VER_FILEVERSION         4.010.03.001609
#define NxpRdLib_VER_FILEVERSION_STR     "4.010.03.001609"
#define NxpRdLib_VER_PRODUCTVERSION      4.010.03.001609
#define NxpRdLib_VER_PRODUCTVERSION_STR  "4.010.03.001609"
#define NxpRdLib_VER_PRODUCT_STREAM (4)
#define NxpRdLib_VER_MAJOR          (1)
#define NxpRdLib_VER_MINOR          (03)
#define NxpRdLib_VER_DEV            (1609)

/* ______GENERATED_FROM____version_info.txt
 * # _____________________________________________________________________________
 * # Product Description
 * #
 * sw_c_define_name = "NxpRdLib"
 * sw_product_name  = "NxpRdLib" # Product Name
 * sw_cs_namespace  = "NxpRdLibNet" # C# Namespace
 * rd_lib_stream    = "06"       # PN7462AU Flavour
 * # NN => Release No.
 * # X => 0 : Library w/o Crypto components
 * #      1 : Library with Crypto components
 * #      2 : Library with Crypto components - Internal usage only.
 * #
 * sw_v_major       = "010"      # Major Release NNX
 * sw_v_minor       = "01"       # SW Minor Version
 * sw_v_dev         = "00"       # SW Development Version
 * sw_maturity      = "B"        # SW Maturity "A" Alpha, "B":Beta, "P": Production
 * sw_metastring    = "uHost"    # Any meta string
 * # _____________________________________________________________________________
 * #
 * # History: Descending
 * #
 * # 06.010.01.00 : Corresponding to PN7462AUFlash_00.02.00_Dev_20140808
 * # 06.010.00.00 : Migrated to UHost/DUT based NxpRdLib
 * # 06.000.01.00 : Intial Release
 * # _____________________________________________________________________________
 */


#endif /* NXPRDLIB_VERSION_INFO_H_INCLUDED */
