/*==============================================================================================
*         Copyright (c), NXP Semiconductors
 *
 *       All rights are reserved. Reproduction in whole or in part is
 *      prohibited without the written consent of the copyright owner.
 *  NXP reserves the right to make changes without notice at any time.
 * NXP makes no warranty, expressed, implied or statutory, including but
 * not limited to any implied warranty of merchantability or fitness for any
 *particular purpose, or that the use will not infringe any third party patent,
 * copyright or trademark. NXP must not be liable for any loss or damage
 *                          arising from its use.
 */

/** \file
* Example Source for Card product type detection.
* $Author:Bharamappa Khatagalli(nxp62726)$
* NxpNfcRdLib_R_Gate_V4.010.00.001602_ExC $Revision: 2673 $
* $Date: 2015-12-04 15:12:35 +0530 (Fri, 04 Dec 2015) $
*
* History:
* BK: Generated 25. Sept 2014
*
*/

/*----------------------------------------------------------------------------------------------
 * Includes
 ---------------------------------------------------------------------------------------------*/
#include <ph_TypeDefs.h>
#include <phhalHw.h>
#include <ph_NxpBuild.h>
#include <ph_Status.h>
#include <phOsal.h>

#include <phhwConfig.h>

#ifdef LPC11U6x  /* this define is defined in project properties -> symbols */
#include <chip.h>
#include <phLpc11u68_Build.h>
#endif /* LPC17xx */


/*----------------------------------------------------------------------------------------------
 * Local macros and definitions
 ---------------------------------------------------------------------------------------------*/
#if defined (NXPBUILD__PHHAL_HW_RC523) && defined (NXPBUILD__PHHAL_HW_RC663)
#error ** Mismatch reader device - PN512 and RC663 are enabled together **
#endif

#define BLUEBOARD_RC663_VER_3_0
//#define BLUEBOARD_RC663_VER_5_0

#if defined (BLUEBOARD_RC663_VER_5_0) && defined (BLUEBOARD_RC663_VER_3_0)
#error ** Mismatch reader device - Blueboard RC663 version 3.0 and 5.0 together **
#endif

/*----------------------------------------------------------------------------------------------
 * Global variables
 * -------------------------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------------------------
 * Local variables
 * -------------------------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------------------------
 * Local function declaration
 ---------------------------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------------------------
 * Global function prototypes
 ---------------------------------------------------------------------------------------------*/


/* **************************************
 * Initialize interface link            *
 * **************************************/

/* =============================================================================================
 * Function:    Set_Interface_Link
 *
 * brief:
 *   Initialize interface link
 *   GPIOSetDir sets the direction in GPIO port.
 *   1 out, 0 input
 *
 *   GPIOSetValue sets/clears a bitvalue in a specific bit position
 *   in GPIO portX(X is the port number.)
 *   Our RC523 will act in slave mode. START and STOP conditions are
 *   generated by the master.
 *
 * -------------------------------------------------------------------------------------------*/
void Set_Interface_Link(void)
{

#if defined NXPBUILD__PHHAL_HW_RC523
#ifdef SPI_USED
    /* note any pinout setting from reason the PNEV512B has interface setting realized
     * by solder resistors on the PCB
     */
#endif /* SPI_USED */
#ifdef I2C_USED

	/* Set direction of pins as output to set for I2C address of attached reader */
	Chip_GPIO_SetPinDIROutput(LPC_GPIO, PORT_AD0, PIN_AD0);
	Chip_GPIO_SetPinDIROutput(LPC_GPIO, PORT_AD1, PIN_AD1);
	Chip_GPIO_SetPinDIROutput(LPC_GPIO, PORT_AD2, PIN_AD2);

	/* Set PN512 I2C address to 0x50 */
	Chip_GPIO_SetPinState(LPC_GPIO, PORT_AD0, PIN_AD0, SET_LOW);
	Chip_GPIO_SetPinState(LPC_GPIO, PORT_AD1, PIN_AD1, SET_LOW);
	Chip_GPIO_SetPinState(LPC_GPIO, PORT_AD2, PIN_AD2, SET_LOW);
#endif /* I2C_USED */
#endif /* NXPBUILD__PHHAL_HW_RC523 */

#if defined NXPBUILD__PHHAL_HW_RC663
#ifdef SPI_USED

	/* Set MCU pin connected to IFSEL0 to output */
    Chip_GPIO_SetPinDIROutput(LPC_GPIO, PORT_IFSEL0, PIN_IFSEL0);

    /* Set MCU pin connected to IFSEL1 to output */
    Chip_GPIO_SetPinDIROutput(LPC_GPIO, PORT_IFSEL1, PIN_IFSEL1);

    /* Select SPI link -> IFSEL0 = 0 & IFSEL1 = 1 */
    /* IFSEL0 = 0 */
    Chip_GPIO_SetPinState(LPC_GPIO, PORT_IFSEL0, PIN_IFSEL0, SET_LOW);

    /* IFSEL1 = 1 */
    Chip_GPIO_SetPinState(LPC_GPIO, PORT_IFSEL1, PIN_IFSEL1, SET_HIGH);

#endif /* SPI_USED */

#ifdef I2C_USED

    /* Set MCU pin connected to IFSEL0 to output */
    Chip_GPIO_SetPinDIROutput(LPC_GPIO, PORT_IFSEL0, PIN_IFSEL0);

    /* Set MCU pin connected to IFSEL1 to output */
    Chip_GPIO_SetPinDIROutput(LPC_GPIO, PORT_IFSEL1, PIN_IFSEL1);

    /* Select I2C link -> IFSEL0 = 1 & IFSEL1 = 0 */
    /* IFSEL0 = 1 */
    Chip_GPIO_SetPinState(LPC_GPIO, PORT_IFSEL0, PIN_IFSEL0, SET_HIGH);

    /* IFSEL1 = 0 */
    Chip_GPIO_SetPinState(LPC_GPIO, PORT_IFSEL1, PIN_IFSEL1, SET_LOW);

    /* Set port pin MCU pin connected to AD0 to output */
    Chip_GPIO_SetPinDIROutput(LPC_GPIO, PORT_AD0, PIN_AD0);

    /* Set port pin MCU pin connected to AD1 to output */
    Chip_GPIO_SetPinDIROutput(LPC_GPIO, PORT_AD1, PIN_AD1);

    /* Select I2C adresss -> AD0 = AD1 = 0 */
    /* AD0 = 0 */
    Chip_GPIO_SetPinState(LPC_GPIO, PORT_AD0, PIN_AD0, SET_LOW);

    /* AD1 = 0 */
    Chip_GPIO_SetPinState(LPC_GPIO, PORT_AD1, PIN_AD1, SET_LOW);
#endif /* I2C_USED */

#endif /* NXPBUILD__PHHAL_HW_RC663 */
}

/*==============================================================================================
 * Function:    Reset_reader_device
 *
 * brief:   This function resets an attached reader IC. In PIN_RESET macro is a correct pin .
 *
 * -------------------------------------------------------------------------------------------*/
void Reset_reader_device(void)
{
uint32_t volatile i;

#if defined NXPBUILD__PHHAL_HW_RC523
	/* Set reset pin as GPIO pin */
    Chip_IOCON_PinMux(LPC_IOCON, PORT_RST_DEV, PIN_RST_DEV, IOCON_MODE_INACT, IOCON_FUNC0);

    /* Reset for PN512 is 1-0-1 */
    /* Set port pin to output */
	Chip_GPIO_SetPinDIROutput(LPC_GPIO, PORT_RST_DEV, PIN_RST_DEV);

    /* RSET signal high */
	Chip_GPIO_SetPinState(LPC_GPIO, PORT_RST_DEV, PIN_RST_DEV, SET_HIGH);

    /* delay of 1 ms */
    for (i = 0x2800; i > 0; i --);

    /* RSET signal low to Reset PN512 */
    Chip_GPIO_SetPinState(LPC_GPIO, PORT_RST_DEV, PIN_RST_DEV, SET_LOW);

    /* delay of 1 ms */
    for (i = 0x2800; i > 0; i --);

    /* RSET signal high */
    Chip_GPIO_SetPinState(LPC_GPIO, PORT_RST_DEV, PIN_RST_DEV, SET_HIGH);

    /* delay of 1 ms */
    for (i = 0x2800; i > 0; i --);
#endif
#if defined NXPBUILD__PHHAL_HW_RC663
    /* Set reset pin as GPIO pin */
    Chip_IOCON_PinMux(LPC_IOCON, PORT_RST_DEV, PIN_RST_DEV, IOCON_MODE_INACT, IOCON_FUNC0);

    /* Set RC663 PDOWN pin to output */
    Chip_GPIO_SetPinDIROutput(LPC_GPIO, PORT_RST_DEV, PIN_RST_DEV);

    /* send the reset pulse 0-1-0 to reset device */
    /* RSET signal low - PDOWN to '0' */
    Chip_GPIO_SetPinState(LPC_GPIO, PORT_RST_DEV, PIN_RST_DEV, SET_LOW);

    /* delay of ~1,2 ms */
    for (i = 0x2800; i > 0; i --);

    /* RSET signal high to reset the RC663 IC - PDOWN to '1' */
    Chip_GPIO_SetPinState(LPC_GPIO, PORT_RST_DEV, PIN_RST_DEV, SET_HIGH);

    /* delay of ~1,2 ms */
    for (i = 0x2800; i > 0; i --);

    /* RSET signal low - PDOWN to '0' */
    Chip_GPIO_SetPinState(LPC_GPIO, PORT_RST_DEV, PIN_RST_DEV, SET_LOW);

    /* delay of ~1,2 ms */
    for (i = 0x2800; i > 0; i --);

#endif
}
/* **************************************
 * handle GPIO                          *
 * **************************************/

/*==============================================================================================
 * Function:    GPIO_Init
 *
 * brief:
 *
 * -------------------------------------------------------------------------------------------*/
void GPIO_Init(void)
{
    /* there is a different name for the GPIO driver module for each LPC processor which comes
     * from drivers.
     * GPIO interface is consolidated via this function calling.
     */

	Chip_GPIO_Init(LPC_GPIO);
}

/*==============================================================================================
 * Function:    Set_Port
 *
 * brief:
 *
 * -------------------------------------------------------------------------------------------*/
void Set_Port(void)
{
#ifndef TUSA
	/* Set the LED pin as output */
	Chip_GPIO_SetPinDIROutput(LPC_GPIO, PORT_LED, PIN_LED);
#endif
}

/*==============================================================================================
 * Function:    LedOn
 *
 * brief:   switch the LED on
 *
 * -------------------------------------------------------------------------------------------*/
void LedOn(void)
{
	Chip_GPIO_SetPinState(LPC_GPIO, PORT_LED, PIN_LED, LED_ON);
}

/*==============================================================================================
 * Function:    LedOff
 *
 * brief:   switch the LED off
 *
 * -------------------------------------------------------------------------------------------*/
void LedOff(void)
{
	Chip_GPIO_SetPinState(LPC_GPIO, PORT_LED, PIN_LED, LED_OFF);
}

#ifdef NXPBUILD__PHHAL_HW_RC523
/*==============================================================================================
 * Data structure dedicated to keep important data from application.
 *
 * params:      pHal    [in]    Pointer to RdLib HAL data parameter component. Its used to handle
 *                              registers of reader IC when configured the interrupts by the Set_Interrupt()
 *                              function.
 *              pOsal   [in]    Pointer to OSAL parameter component. Necessary to call a correct
 *                              application callback from within timer interrupt handler.
 *              pData   [in]    Pointer to data from the application. The data are expected to be
 *                              handled within IRQ handlers of this project.
 * -------------------------------------------------------------------------------------------*/
static struct
{
    void            *pHal;
    void            *pOsal;
    volatile void   *pData_ready;
    volatile void   *pExitLoopback;
}appData;

/*==============================================================================================
 * Function:    appDataInit
 *
 * brief:       This function configures pin IRQ on MCU side and IRQ generation on reader IC.
 *              In result dedicated interrupt requests from reader IC are escalated to the host MCU.
 *              The function is used by NFC Target.
 *
 * params:      pHal    [in]    Pointer to RdLib HAL data parameter component. Its used to handle
 *                              registers of reader IC when configured the interrupts by the Set_Interrupt()
 *                              function.
 *              pOsal   [in]    Pointer to OSAL parameter component. Necessary to call a correct
 *                              application callback from within timer interrupt handler.
 *              pData   [in]    Pointer to data from the application. The data are expected to be
 *                              handled within IRQ handlers of this project. *
 * -------------------------------------------------------------------------------------------*/
void appDataInit( void  *pHal,
                  void  *pOsal,
                  void  *pData,
                  void  *pExitLoopback)
{
    appData.pHal              = pHal;
    appData.pOsal             = pOsal;
    appData.pData_ready       = pData;
    appData.pExitLoopback     = pExitLoopback;

    return;
}
#endif /* NXPBUILD__PHHAL_HW_RC523 */
/*==============================================================================================
 * Function:    Set_Interrupt
 *
 * brief:       This function is called when interrupt from attached PN512 IC occurs.
 *              It resets MCU and reader IC to state to be able to detect another IRQ.
 *
 * -------------------------------------------------------------------------------------------*/
void Set_Interrupt(void)
{
	/* Global Enable Interrupts */
	__enable_irq();

#ifdef LPC11U6x
    /* Configure the LPC11U6x GPIO pin connected to IRQ pin of reader IC as input pin */
    Chip_GPIO_SetPinDIRInput(LPC_GPIO, PORT_EXT_IRQ, PIN_EXT_IRQ);

    /* configure IOCON 0th divider */
	Chip_Clock_SetIOCONFiltClockDiv(0, 1);

    /* Configure pin as GPIO with pullup and use optional IOCON divider
 		0 with 3 filter clocks for input filtering */
	Chip_IOCON_PinMuxSet(LPC_IOCON, PORT_EXT_IRQ, PIN_EXT_IRQ,
    		 (IOCON_FUNC0 |
    		  IOCON_MODE_PULLUP |
			  IOCON_CLKDIV(0) |
			  IOCON_S_MODE(1)));

    Chip_Clock_EnablePeriphClock(SYSCTL_CLOCK_PINT);

    /* Configure interrupt channel for the GPIO pin in SysCon block
     * In drivers 2v06 there is a bug in Chip_SYSCTL_SetPinInterrupt(), thus must be set manually here*/
	LPC_SYSCTL->PINTSEL[0] = (uint32_t) (24 + PIN_EXT_IRQ);

    /* Configure channel interrupt as edge sensitive and falling edge interrupt */
    Chip_PININT_ClearIntStatus(LPC_PININT, PININTCH(0));
    Chip_PININT_SetPinModeEdge(LPC_PININT, PININTCH(0));
    Chip_PININT_EnableIntLow(LPC_PININT,  PININTCH(0));

    NVIC_SetPriority(EXTERNAL_IRQ, PRIORITY_EXT_IRQ);
    /* Enable interrupt in the NVIC */
    NVIC_ClearPendingIRQ(EXTERNAL_IRQ);
    NVIC_EnableIRQ(EXTERNAL_IRQ);
#endif /* LPC11U6x */

    return;
}

/*==============================================================================================
 * Function:    PIN_INT0_IRQHandler
 *
 * brief:
 *
 * -------------------------------------------------------------------------------------------*/
void CLIF_IRQHandler(void)
{
	uint32_t    regVal;
	uint16_t    status = 0;

#ifdef LPC11U6x
	/* Read the interrupt status of external interrupt attached to the reader IC IRQ pin */
	regVal = Chip_PININT_GetIntStatus(LPC_PININT);
	if (regVal == 1)
	{
		status = phOsal_Event_Post(E_PH_OSAL_EVT_RF, E_PH_OSAL_EVT_SRC_ISR, E_PH_OSAL_EVT_DEST_HAL);
		CHECK_STATUS(status);
	}
	Chip_PININT_ClearIntStatus(LPC_PININT, PININTCH0);
#endif /* LPC11U6x */

	return;
}

/*----------------------------------------------------------------------------------------------
 * End of file
 ---------------------------------------------------------------------------------------------*/
